- README.md
a few minor formatting suggestions for the README
> minor formatting

- environment.yml
> Add jupyterlab and extensions to environment.yml

- .github/workflows/ci.yml
- devtools/regenerate_readmes.py
- teachopencadd/talktorials/000_template/README.md
- teachopencadd/talktorials/001_query_chembl/README.md
- teachopencadd/talktorials/002_compound_adme/README.md
- teachopencadd/talktorials/003_compound_unwanted_substructures/README.md
- teachopencadd/talktorials/004_compound_similarity/README.md
- teachopencadd/talktorials/005_compound_clustering/README.md
- teachopencadd/talktorials/006_compound_maximum_common_substructures/README.md
- teachopencadd/talktorials/007_compound_activity_machine_learning/README.md
- teachopencadd/talktorials/008_query_pdb/README.md
- teachopencadd/talktorials/009_compound_ensemble_pharmacophores/README.md
- teachopencadd/talktorials/010_binding_site_comparison/README.md
- teachopencadd/talktorials/011_query_online_api_webservices/README.md
- teachopencadd/talktorials/012_query_pubchem/README.md
- teachopencadd/talktorials/013_query_klifs/README.md
- teachopencadd/talktorials/014_binding_site_detection/README.md
- teachopencadd/talktorials/015_protein_ligand_docking/README.md
- teachopencadd/talktorials/016_protein_ligand_interactions/README.md
- teachopencadd/talktorials/017_python_jupyter_introduction/README.md
> Add script to automatically regenerate READMEs from talktorials

- README.md
Add disclaimer to `packaging` README that comments on the major changes in the future version 2020.12.01 and refers back to the last release in the `v1.x` series.
> Add disclaimer (new > old release)

- teachopencadd/talktorials/T003_compound_unwanted_substructures/talktorial.ipynb
> T003: Fix typo Brank > Brenk

- docs/external_resources.rst
> Add link to best practices slides

- README.md
Add cool badges.
See https://shields.io/category/issue-tracking for full list.
> Add badges to README top

- devtools/other-conda-envs/users_env.yml
- devtools/test_env.yml
`opencadd` is `conda`-installable now :partying_face: Let's use it :rocket: 
None
> Install opencadd from conda!

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- README.md
Update README + add PR template.
None
> Update README + add PR template

- README.md
- docs/external_resources.rst
- docs/index.rst
> Update README and docs

- teachopencadd/talktorials/T001_query_chembl/talktorial.ipynb
Update explanatory text in T001.
None.
> T001: Update explanatory text

- README.md
> Fix Docs CI

- README.md
Change badge from MIT to CC-BY-4.0 .
Taken from here: https://gist.github.com/qvil/5e3ed56c26d784e51424621119cc4028
> Update license badge.

- README.md
Since there is a conda package of TeachOpenCADD :) 
Taken from here https://anaconda.org/conda-forge/teachopencadd/badges
> Conda badge

- teachopencadd/talktorials/T018_automated_cadd_pipeline/README.md
T018's widget states were not saved. Fix it :)
None.
> T018: Rerun notebook with saved widget states

- README.md
Update README to reflect the latest major 2021.12 release!
None.
> Update README with 2021.12 release notes!

- docs/index.rst
- docs/talktorials.rst
Update website with a few minor things.
> Update website (2021 collection + open website disclaimer)

- docs/installing.rst
Apply suggestion: https://github.com/volkamerlab/opencadd/issues/126
> Update install details with conda-forge channel

- .github/workflows/ci.yml
This PR will trigger GitHub actions runs on weekly bases.
> Run ci on weekly bases

- .github/workflows/docs.yml
Test docs every week on monday.
> Test docs every week on monday

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- README.md
Fix the github star link to fix DOCS workflow.
> fix github star link

- README.md
Update citation list + description on which citation to use when.
> Update citations (NAR, LiveCoMS)

- teachopencadd/talktorials/T007_compound_activity_machine_learning/talktorial.ipynb
While using talktorial T007, I came across this minor issue in the description of the number of layers and neurons.
Keep up the great work 👍
> FIX: correction description num layers and neurons (hidden_layer_sizes)

- docs/installing.rst
Update installing documentation.
> Docs: Update installing documentation

- devtools/test_env.yml
Pin `ipywidgets` < 8 to solve #262
> Pin `ipywidgets` < 8 to solve #262

- README.md
Update Zenodo badge (pointed to first TOC release, now points to general/latest TOC release).
> README: Update Zenodo badge

- .github/PULL_REQUEST_TEMPLATE/talktorial_review.md
We had a PR template tailored for refactoring talktorials; extend this template to be helpful when adding new talktorials or extending existing talktorials.
> Extend PR template (for new talktorials)

- .github/workflows/ci.yml
- devtools/test_env.yml
Check if we can unpin `jsonschema` since this issue should be fixed: https://github.com/Yelp/bravado/issues/478
Should fix: https://github.com/volkamerlab/teachopencadd/issues/152
> T011/12: Remove pinned `jsonschema` from env

- .github/workflows/ci.yml
- teachopencadd/talktorials/T022_ligand_based_screening_neural_network/talktorial.ipynb
Fix #289 and investigate how env for T021 and T022 could work.
> T021/22: Run under global environment

- README.md
Follow up on open TODOs from PR #315: In README, link to new website pages.
This closes issue #316
> README: Link to new website pages

- .github/workflows/ci.yml
T020 does not work under Mac. See #364.
> 364 t020 not working under mac os

- .github/workflows/docs.yml
- teachopencadd/talktorials/T033_molecular_representations/talktorial.ipynb
- teachopencadd/talktorials/T037_uncertainty_estimation/talktorial.ipynb
> Docs CI: ignore some 403 in linkcheck

- .github/workflows/ci.yml
- .github/workflows/docs.yml
Monthly CI runs instead of weekly ones.
> CI: monthly instead of weekly CI runs

- README.md
- docs/index.rst
- teachopencadd/talktorials/T033_molecular_representations/README.md
- teachopencadd/talktorials/T033_molecular_representations/talktorial.ipynb
- teachopencadd/talktorials/T034_recurrent_neural_networks/README.md
- teachopencadd/talktorials/T034_recurrent_neural_networks/talktorial.ipynb
- teachopencadd/talktorials/T035_graph_neural_networks/README.md
- teachopencadd/talktorials/T035_graph_neural_networks/talktorial.ipynb
- teachopencadd/talktorials/T036_e3_equivariant_gnn/README.md
- teachopencadd/talktorials/T036_e3_equivariant_gnn/talktorial.ipynb
- teachopencadd/talktorials/T037_uncertainty_estimation/README.md
- teachopencadd/talktorials/T037_uncertainty_estimation/talktorial.ipynb
- teachopencadd/talktorials/T038_protein_ligand_interaction_prediction/README.md
- teachopencadd/talktorials/T038_protein_ligand_interaction_prediction/talktorial.ipynb
Linked NextAID in DL talktorials (see https://github.com/volkamerlab/teachopencadd/issues/392)
> [DL Edition] Changes in author information

- docs/installing.rst
- teachopencadd/talktorials/T015_protein_ligand_docking/README.md
- teachopencadd/talktorials/T015_protein_ligand_docking/talktorial.ipynb
- teachopencadd/talktorials/T018_automated_cadd_pipeline/README.md
> fix mamba install link, openbabel links
