- README.md
Add more obvious notice on how to cite/highlight TeachOpenCADD usage at the top of README.
None.
> Add more obvious notice on citation in README

- .github/workflows/ci.yml
hey folks -- sorry to say, due to my google cloud credits running out and a misunderstanding, my GCP account has just been nuked and uploads are out of action.
I should be able to retrieve any stored data if you need but this is likely a permanent change as I was planning on deprecating the backend.
Again, sorry for the lack of warning. Fortunately I have a more open replacement to this capability coming very soon.
> remove treebeard API key

- teachopencadd/talktorials/T000_template/talktorial.ipynb
- Talktorial ID: T000
- Title: Talktorial template
- Original authors: @dominiquesydow 
- Reviewer(s): @AndreaVolkamer 
- Date of review: 15.12.2020
Update template w.r.t. @AndreaVolkamer's suggestions (that she send via PM - copied here):
- Clear output and rerun, does it finish without errors?
- Deterministic behavior/output? (help with CI comments)
- Check runtime?
> T000 - Talktorial template

- docs/_static/custom.css
Before fix:
After fix (`molecules` is no longer covered by the unwanted scrollbar):
---
Thanks @bra1n for the fix!
> Fix unwanted scrollbars in Edge Legacy

- teachopencadd/talktorials/T015_protein_ligand_docking/README.md
- teachopencadd/talktorials/T015_protein_ligand_docking/talktorial.ipynb
This PR adds a visual inspection section to the Theory of the docking talktorial. The section is based on the newly published paper in [J Med Chem](https://pubs.acs.org/doi/10.1021/acs.jmedchem.0c02227).
> adds visual inspection to docking theory

- README.md
Add missing packages from T001-22.
> Add missing packages from T001-22 to README

- .github/workflows/ci.yml
- devtools/other-conda-envs/users_env.yml
- devtools/test_env.yml
See issue: https://github.com/volkamerlab/teachopencadd/issues/150
- Python 3.6 support may become more and more complicated with that many packages we are using
- Examples
- https://github.com/volkamerlab/teachopencadd/pull/146
- https://deeptalk.lambdalabs.com/t/cant-build-keras-model-after-tensorflow-update-from-2-2-to-2-3/1799
- https://bugs.gentoo.org/806541 
None
> Add `numpy`+`jsonschema` to env + drop Python 3.6 in CI (use 3.7 instead)

- .github/workflows/ci.yml
- devtools/test_env.yml
- teachopencadd/cli.py
- teachopencadd/tests/test_cli.py
- teachopencadd/utils.py
Add `teachopencadd start workspace` CLI that copies talktorials from their location in the `teachopencadd` package to a user-defined folder (**workspace**).
`teachopencadd start .` will copy the [full talktorial folder content](https://github.com/volkamerlab/teachopencadd/tree/master/teachopencadd/talktorials) to a folder called `teachopencadd-talktorials`, which lives in the user-defined workspace (here: working directory `.`)
Copy files, list talktorials, give JLab instructions.
```
$ teachopencadd start ~/workspaces
___                _               _       _   _  
|  _   _.  _ |_  / \ ._   _  ._  /   /\  | \ | \ 
| (/_ (_| (_ | | \_/ |_) (/_ | | \_ /--\ |_/ |_/ 
|                           
version v1.3.0+705.g394f25c
by @volkamerlab
Talktorials available in your workspace:
- …
```
> Add `teachopencadd start workspace` CLI

- teachopencadd/cli.py
- teachopencadd/tests/test_cli.py
The TeachOpenCADD greeting is printed twice when using `teachopencadd` or `teachopencadd -h`. Remove the greeting in these instances (easier than reducing the output to one greeting).
None.
> Fix CLI bug (greeting printed twice)

- docs/contribute.rst
Extend the information for potential contributors on our website.
None.
> Docs: Extend contributors details

- devtools/test_env.yml
- docs/installing.rst
Under Windows, we cannot install `tensorflow >=2` via conda-forge. We need to add the `defaults` channel.
None.
> Add `defaults` conda channel (needed for installations under Windows)

- devtools/test_env.yml
- docs/conf.py
Add the `opengraph` sphinx extension to render previews when we post our website's link. 
https://github.com/wpilibsuite/sphinxext-opengraph
None.
> Add opengraph to test env + docs conf.py

- docs/conf.py
Update opengraph image URL since image is not shown in website preview! 
I think we need the raw URL path:
https://raw.githubusercontent.com/volkamerlab/teachopencadd/master/docs/_static/images/TeachOpenCADD_topics.png
None.
> Update opengraph image URL

- devtools/test_env.yml
This PR investigates recent failures of the CI when using the PandasTools from RDKit (#204).
> Fix pandas failure

- docs/installing.rst
Update installation instructions; see user experience by @magattaca:
https://magattaca.hatenablog.com/entry/2021/12/31/003600
> Update installation instructions

- .github/workflows/ci.yml
- teachopencadd/talktorials/T018_automated_cadd_pipeline/utils/binding_site_detection.py
- teachopencadd/talktorials/T018_automated_cadd_pipeline/utils/helpers/nglview.py
- teachopencadd/talktorials/T018_automated_cadd_pipeline/utils/helpers/obabel.py
Small fixes for T018 pipeline issues and CI Python 3.9 issues.
> Fixes for protonation of protein and binding site detection

- .github/workflows/docs.yml
- README.md
- devtools/test_env.yml
Pin jinja2 to fix failing docs:
https://github.com/volkamerlab/teachopencadd/runs/5686402020?check_suite_focus=true#step:8:42
Note: In this PR, only the docs CI needs to pass.
> Pin jinja2 to fix failing docs

- devtools/test_env.yml
This PR fixes the RDKit kekulize error by pinning RDKit.
> Pin rdkit to fix kekulize error

- teachopencadd/talktorials/T019_md_simulation/talktorial.ipynb
T019 wasn't satisfying `black-nb`, addressed in #240 .
> Fix black-nb in T019

- README.md
Update README (release news section).
> README: Add paper links to latest release news

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- devtools/test_env.yml
- teachopencadd/talktorials/T009_compound_ensemble_pharmacophores/talktorial.ipynb
Bump up our Python requirements to Python 3.8 (i.e. dropping support for 3.7).
See discussion here: https://github.com/volkamerlab/teachopencadd/issues/252
> Python requirements >= 3.8

- teachopencadd/talktorials/T025_kinase_similarity_kissim/talktorial.ipynb
- teachopencadd/talktorials/T026_kinase_similarity_ifp/talktorial.ipynb
T025+26: Apparently, the default figure size increased from 432x288 to 640x480 (in Jupyter Lab and Notebook). 
- I am dropping the `nbval` check because I think it is enough to be informed if the cell fails instead of if the string `(<Figure size 432x288 with 1 Axes>, <AxesSubplot:>)` changes; both figure sizes are fine :) 
- FYI, we are not `nbval`-checking plots in other talktorials. I might have missed some cases, but we usually do not.
> CI: Drop figure size `nbval` check

- .github/workflows/ci.yml
- devtools/test_env.yml
While looking into the `tensorflow` issue reported in https://github.com/volkamerlab/teachopencadd/issues/265, I noticed that we are running the CI for Windows under Py3.9 although we intended to run all platforms by default under Py3.8 (plus an additional test for Py3.9 under Linux).
I introduced this discrepency when I made a CI test run for Win Py3.9 and forgot (?) to revert back to Py3.8: https://github.com/volkamerlab/teachopencadd/pull/254#issuecomment-1191507478 (the exact commit: https://github.com/volkamerlab/teachopencadd/commit/f1596b4171d623145935e64d32c26a8db4560201)
Pin `tensorflow` version matching the API used in T021 and T022 (i.e. 2.6).
> CI: Revert Win Py3.9 back to Py3.8; pin `tensorflow`<=2.6

- README.md
Update broken anaconda badge link, change
https://anaconda.org/conda-forge/teachopencadd/badges/installer/conda.svg
to
https://anaconda.org/conda-forge/teachopencadd/badges/downloads.svg
> README: Fix broken anaconda badge/link

- docs/index.rst
- docs/installing.rst
TeachOpenCADD citations on website are out-of-date. Remove existing text and only link to README citation section, which is up-to-date.
> Docs: Update TeachOpenCADD citations

- docs/installing.rst
Docs: Add more MacOS/M1 install instructions
> Docs: Add more MacOS/M1 install instructions

- README.md
- docs/conf.py
- docs/contribute.rst
Add a more detailed contribution guide for TeachOpenCADD.
https://projects.volkamerlab.org/teachopencadd/contribute.html
Use conda-forge documentation as template?
> Add TeachOpenCADD contribution guide

- .github/workflows/ci.yml
- devtools/test_env.yml
Fix `AttributeError: module 'numpy' has no attribute 'typeDict'` for T008/10/15/16/18/20.
https://github.com/volkamerlab/teachopencadd/issues/299
Example: T008 fails for all OS and Python versions:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 21
18 from rdkit.Chem import Draw
19 from rdkit.Chem import PandasTools
---> 21 from opencadd.structure.superposition.api import align, METHODS
22 from opencadd.structure.core import Structure
24 # Disable some unneeded warnings
File C:\Miniconda\envs\teachopencadd\lib\site-packages\opencadd\structure\superposition\api.py:7
5 from .engines.theseus import TheseusAligner
6 from .engines.mmligner import MMLignerAligner
----> 7 …
```
> T008/10/15/16/18/20: AttributeError: module 'numpy' has no attribute 'typeDict'

- .github/workflows/ci.yml
- teachopencadd/talktorials/T008_query_pdb/README.md
- teachopencadd/talktorials/T008_query_pdb/talktorial.ipynb
T008 won't work in Jan 2023 because of https://github.com/volkamerlab/teachopencadd/issues/303
> T008: Remove from CI in Jan 2023

- .github/workflows/ci.yml
- devtools/test_env.yml
- teachopencadd/talktorials/T008_query_pdb/README.md
- teachopencadd/talktorials/T008_query_pdb/talktorial.ipynb
- teachopencadd/talktorials/T019_md_simulation/talktorial.ipynb
- teachopencadd/talktorials/T022_ligand_based_screening_neural_network/talktorial.ipynb
Current `teachopencadd` has a couple of dependency conflicts and deps-unrelated `pytest` fails.
This base branch shall be used to get a fully passing CI, while fixing all the different bits and pieces in smaller PRs.
- #303 --- do not close before at least Feb
- Fixed in https://github.com/volkamerlab/teachopencadd/pull/296/commits/eccb30addd07f6a6ec30acf16c25ba108cbc62a1
- Seems fine, all tests are passing as before after https://github.com/volkamerlab/teachopencadd/pull/296/commits/6d8e5015fdc5145f52bb1180de27b5f28cf86e2a
...continue with TODOs in #312
> Base branch for CI/env fixes

- README.md
- docs/acknowledgments.rst
- docs/citation.rst
- docs/conf.py
- docs/contact.rst
- docs/contribute.rst
- docs/external_dependencies.rst
- docs/external_tutorials_collections.rst
- docs/funding.rst
- docs/index.rst
- docs/installing.rst
- docs/license.rst
Currently, we have documentation scattered between our TeachOpenCADD website (referred to here as "[docs](https://projects.volkamerlab.org/teachopencadd/)") and our repository [README](https://github.com/volkamerlab/teachopencadd/blob/master/README.md). Move most of the content from README to docs & add missing bits and pieces as outlined below.
> Update TeachOpenCADD website (docs) and repo README

- .github/workflows/ci.yml
- .github/workflows/docs.yml
CI fails again with un-descriptive conda error message:
`Error: The process '/usr/share/miniconda/condabin/conda' failed with exit code 1`
See discussion here: https://github.com/conda-incubator/setup-miniconda/issues/116#issuecomment-1385554002
-> Might be resolved by using `mambaforge` instead of mamba as resolver.
> CI fails again with un-descriptive conda error message

- .github/workflows/docs.yml
Switch from `broken-link-checker` to `linkinator`. The former seems to be dead.
> Docs CI: switch to linkinator

- devtools/test_env.yml
- teachopencadd/talktorials/T018_automated_cadd_pipeline/utils/helpers/nglview.py
- teachopencadd/talktorials/T018_automated_cadd_pipeline/utils/helpers/pdb.py
- teachopencadd/talktorials/T018_automated_cadd_pipeline/utils/ligand.py
- teachopencadd/talktorials/T018_automated_cadd_pipeline/utils/protein.py
This PR solves the problems in T018.
> T018: deprecation warnings and images not showing (#334)

- devtools/test_env.yml
See #389. This PR moves the DL packages to the back of the depency list in `devtools/test_env.yml`.
> Environment package ordering

- docs/installing.rst
This adds a short note to the conda install instructions on the missing DL edition packages.
> Install docs: add a note about missing dl packages

- README.md
Workflows have been moved which has invalidated the links. This PR updates the links to the most current version, which we will make sure to keep intact in the future.
> Update links to KNIME workflows
